
name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - run: npm ci

      # Additional steps for resolving dependencies
      - name: Check npm audit
        run: npm audit  # Check for vulnerabilities

      - name: Check npm outdated
        run: npm outdated  # Check for outdated dependencies

      - name: Update dependencies if necessary
        run: |
          # Update specific dependencies to resolve conflicts
          npm install package-name@latest --save-dev

      # Retry npm ci after resolving dependencies
      - run: npm ci

      # Additional steps for testing or building the code
      - run: npm run build --if-present

